### ISSUE TITLE
when fetching bugs, filter bugzilla products by component

### ISSUE THREAD

**Issue by MaximilianMeister** [openSUSE/nailed#68]
example: we want to only show openSUSE Kubic bugs, which are a component of openSUSE Tumbleweed

would be nice if it's configurable like e.g.:

```yaml
products: # list of exact product names as they appear on bugzilla
  - SUSE CaaS Platform 4
  - openSUSE_Tumbleweed:
      component: Kubic
```
